sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global: 
dd:
  secure: v6U43bq2ZQIagaW4hOsts25CbVOvA7lrn++tJ8fBQ+puoHYCF2iue+tpU9ifWVwEKlDhl9NyzO7aKi/+MBe0MbgoSzAioBLKxQb7mRzlvVFrtWhR9injt8Ll2aFf0j7+9tTmUGBk/OZ6FeY2zt0v/iRnlwqgG4o2lIGE3YGd820TXVdjrOnccBm3YDPREgdY+CYFqcFfULb7JLhWg2QIUWz/rVpp0JYhq7AneUemEKh0nCkDgBwc7j7sVsOGOU4kc0296cgxNjKeBpJOhdqm+uscLxY1UPyucABLV21RuspJRtsvlMuzJNedrZbVCweS0Q43sGOVUAi6Eo4NcT/8sPdJWsC4xAdoFh9iwEAx8Hwmc30iTb9TriK2pmyUO/vouQhGPqOzxO5YYFHLcrVp667wfw+qqIXk84wiujBnVoLdeA0cX/aeKtRdYiUjMBftJXkJfAv99Z712P5NMa+WWhZm1dmQ4Y0eIx0Pzww8qe1Yf1jnm19tIQgXjugAn4eubUD0bNFSEmeYUoepDOt3wf28MZ6EFQDKk18uuzZTjA0bQnJO3O5t+3Av9q9xJqJkeKxtMp+tsblD9ZHdW4omq0h0EdOPOmiTirJivsyE8AM+cHGQOf++8HDcNMZcMyvRxaVfddsuS86GvRho6N5Dn8+A7ZamBMbc1QZjERK9ies=
