sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global: 
dd:
  secure: geDMZYxzIYkrVjF6OQqMMSVoHBz61ZzDOBrfvnAciyDCctvUdPi9NQoG+WBEt2DheKvJDrJQvBx8l9HPBXcj7dYgyQJnKXayx3YU1wQbBiBZ1sy0XBEv5YRwVTFcIJXpSxF+neh7TMWfOMTLRkJGx43aMAJkUjAacwos6mlGFRRBQJ0Nv26v0J0oRYw/2IFBkVvUSDtEMNZPrsvvMghTzv2EQtRUVaUcZQQKaus/f6HPczFOsFXWxfEhiVRuFDRXuVzdTngRjQyGx7qHfrxVBY4dc+xqHrupJ3Ei2MoXVNCMqFW8ZlZWCtKEroD622ZbDtRV9e8VN3WzVoYjvmmiNVtIfBAo3oZ2prkqwS5IJy2YfFG6LglVgTwTINLaaQFfTUcdz9xPUzZFj6DPGQGpgRCU375x8yFBH5CvwS3p2kBsk6uNt+LKOk+jp8YhDP6FVYHYoZjvFdskcaxkKVHbCnQ51b0XSwAuy4jZNV1EKCAomWKXb6UK6K1LAMYn0wbP0//pPCw7NOYG1sSAncrVLyjfCrEVIkmocANAGMM0UWAaqE8zJVvsX+uiTmubZnhjto2wQynzyjQIV6sJITzjkFJqguHY+AWs6H+dwIhWMTWyNDs5y5Y2ACyfqnGOtpL4feW8y1jEiA+vEWwwVQet5oIxn8hy8lc7LNqfGyOFyn0=
