sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global: 
dd:
  secure: nvDAq0sm1t8ltO2ZVL4b41yR+whrFnbo++jiI5wX4uOFUQSo6TZ/mBvqa2cd5X6hssGosNrPcI8lMALM7PS1hyWh0kYb6K/noSMQ4eqKeA5Blp8wEKax1wFjMbavwObbwPnKjZ2inTd/0j1p4guj2n1yYpZcs0hK4po17E2NkFgPInp8IE7ywTYnUxKo2w2YryTSRM67m+6Ij9AHPWKoK7qVopXr/Ezh9833jplQzxrxlALcCrNzlJf0v/Vv3qvnfW9aDp2lxWEkCyAcNno+6UISHXyv/ocJp/adxJY5KLjngDdN/0hjKLRXp6LPWeGCcMa/xFiCm6pdUHHw1phEFAEbpVb/wTY5z2YR1Prj3dszlZm4Kcj0YmPC2qG6SHnx2zH8U69EtkoXKaNO7CzVKQmd//jsm2PEblnpPRnsgOtsInniBsB5z7k3/rMCbmzq22aab1AUCyc+lv+r27xsTRPJhNWa6h/K5BYB6O0oCBP+4GwUbD8uNY4AV0w4sizCdEYEEVhJAkeFU8SnIhuaOxxKX//R6EkAFp2dEenDaBwQNJFUCUVCRXJqXVR9Lybt0vgQ/+l92Pzi4hJkx0jA0n0sjuwuy7Gj48luXxgEyOYmoYvpuqAdaMB/t+YmjWjkhtZEbqViNbOaHK7wc60eV+o8qZ7xIZgUZk9bBZa1mO0=
