sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global: 
dd:
  secure: ZFtH2aeXAVoIrwLHCq4Uu4o562aEEOv4FZlMPQGlSN0g87SOiUJkPJayemEYa+6cU4scsDE/3pnRlpqMXJoQ7F7cSSyAPkuIizLD004AW26kVHec4RXqmDQZbcUUff2JEMVnklKW78yfFEoCA+VENxWdFbmZuRN/xifH+S0ylRQ+tA5fAPvdqyFBZ/BBh9gkNrft/SoXNGTV8W6NBYghW6WbeT84KKgsZuJqiq6/dOfkbxGsFs0GMBhdRNe2Q/WDI0Xv5fskGh4YftGiP0i8zAuYrB71/SLHi9n3+I3mhmDf7Sybaf6Ysp1fJc+gU5YFqru6zbAiclsOxOkeGOVmGoPlxAAaaLgdlyPgBJvPFzUXSB0pH8S8zeccGkNFmCXaQOVOf177oUw9S5mDH6+V/jJ4l4aGu/ivyaeUKjGJTJ4BFgakhTz5jmQHR2CAELcRcrCt1wL1HVQYwGXBf+0Q2/+eSeeplKfHQiim5gjda59PoqWIcXWfUxdxMPbklmJ8VdgtbOY8JPuFPIGk4UXF2p2BFvEIuJ8qFgO/x+ul9mluHGdkrcK48Nta34dTA4b7/35hMfhoVLC5/1ksxuVuoFYbV5SRNh395gN/W4VOm40FFwu9omqMVUBH3CCw/NaWjNeQtGb9B262SITdLrEFW3+XN7pMhfSYTYKIkkWt9Fo=
