sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global: 
dd:
  secure: PiPt4i1g4V5vFXlKA1Fqv+YHUJ9kyqKkoioiqGm64gEgW8nnlpMUlVVckPP9vERTonz1k0FGXNzFgh7Ahl7/sSot+sm1ZfmsWu6+kuYZopgTnp9UBceyNguKeJ3UaP/kjP6E0esPypAvtbSFZdbkRYz5ol2Txwfm1v6pVy1jspUoCmDB+NLr2TncIZaMgB37Od5TekH4We7oKUH1FnonZLxojgd47ASugPUEY0LSMnCk47vHbW+sCvapcbaC8mqlQF5THidZrc3YAkc8B8B5YdhVDzEstEsQj9b0HICcYjlzG1AXzTBDrQIfJ06m+18Q0dKuZPYXarqfGQfuNtL+AEBo+KXdMyEzbXlR3Cao3rwgvcNTrsDu/BDChUpxlUIByPtSvbZtELpj50k4NaAwXK2UKSRdAf8WFzH7W4eVOOZ8TJ5qug88iSdaEEkaSgVqDpDKHQ6pfF6Qdeyp5LhZgVasfYomgqFNglzxp9VpQ7l4gHKoVJV3qUempYQu5LBQE46Ar4J+hwJlBDp+Pu59EgVEk0n3QQIH92Ybx/j6+xfZtl/PoQBfKzfgKOq7xZfHDwvHkPDe50WLiR+1+dvSpS7T2yFtfhtqeygkKeL6fnSL67p8I3+zpXInCSbf3qxjX0YK4rG1YRDLJphTO+gyqMhHLwc2/B2+sFdfXtSt06U=
