sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2
install:
- bundle install
script: bundle exec rake site:deploy --quiet --trace
dd:
  secure: Se20fagJ7S/TM26dS0rgsWglUecnhHWp+icBsS5gWFNZfDMQ7wO+O54dAhR37L1Dzberss+Oir9edQ2VlaRYlroyrQK8QzhDPknARz1/ocDmR5ZWwD8qdUZ51PCaSCKz53ZVGxLsMOPvhgDCTVCAQ5SUApmXJxNSDlYrgBemXTvnZaQ2iVkca4sVMqcIqaqEt2hMCzbYRpYO+uABq17WSBGkdChMYdqzMj3U5ii2Ck7A/OsVFLPK0JUvqmADvif3+/0KfNHo7xO2uvrmCCp7wqDHy/pPdSpflxJnBS3oz0i5MZkIGBl/DFtR//Yd+XnDQLLxqvVovKfVApJs/08Xal5ggYa/UnAD2XvJem4eTLjH6vlIts8L0qhEx+GoC6nI3jhYN/H+Qe35NjuUpGKqiyUYzDuof0TZFqb/9Ro5KyK28BslMeH4IiO9Tr0lcOGYjT3xaEVSEgsPKppzJiQALXajb9ViaJvHQBwQddVcUa236qW1nubTJbKF6L08HzP27Ecneewu/3TilA2xa9wqWyplBSAfM4+UYQTjZlXdnFu/f3WDjntiBUsNXMQxuSKMfHvs+0bLIwMNyRuw73911tG/PjnkFP10c5R9ogvp8ot4waWQSeAMavKcGFFODd1sxnNgYC5vpEENICwJPIhi+WZ77SrZ0i/F7PG2GB2BEnU=
branches:
  only:
  - source
