sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global: 
dd:
  secure: eefu1rNHbQkppX6qBC3w6QRczB54KV89tkHNmIUAj1CigyyfX7OHapzJE8APWiWk1/A4Fj1Hq1XHnaSyveiU8dZXdAlL+r+OwknQTCMnw5bMSizFwJqZXUEHZUWZMdg1XhVGm/L2n5jsu0A1hkYii3kWq9Z6LDGyqzExZY+ev3ZohAYJD/T/79Tf/lLrGzMtuHhAutTN+lbXP4PT/aIcByIkX+/u76MQ5PaM+epCzuJSpmhevj2E+qI0OJ8c3wDVVer3NRUCQK3LyVN+F6z0Xphf0/DYK7deDaaIr4Pt6ujNXgbb9iC/c+Jhx9glnY0gCoA4sW65u/836SHcz7cqvnpY7ozkpr/RCGcm5v0qLjLwfgbMvDGjtCiSc5WbR/YWDf+04eyCbQznwYvNC/xOjgh1ep8/MvwIB5PUrfCuhM4SsrT4X+sgyl8onz/HH5FfjzeRaQSLwx/UOVT9G7jILqj2WXcAeBAp95GCjOvLMX5SX76n3THGlYF5a8KasgaXGl7gQ/iGi3gCZsh/WdQoyW630KKKJ2SVWzwk4Q7WjmOhYyeqRhWaHIZZJeeBWTgffSn/96W4ykUGtlth966RaXrt4WLmpED1HQrVf26JmciQFnbTKmrgO72wy8PaG1hWNk/UcvK7y4ubJx3wCaVuPri37MtVsdn0eHvIVgcibGE=
