sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global: 
dd:
  secure: Urbq7+ufXbn//8wzgwzL8QVQhX1567Kr9jAwtCieNG14XlvqJzrkK+gRdCBsTN6QF+Beogc+djQCQ6F5Yun19R/lVlk4KRtWszfL1UlOVNOeGPU48InjeBlxr0eE6D9LZ1YMtGquI4IPG6WwEVQMMyP2mebpG4Yrikyi4aDmJb0NnknDP6wtxJof8YX9xdnfdsGUens8kW1xd568kUph6tBF1u98Ruf6klDETAZSY5o5pPHZqhwXyyhxDu7WqtVh3ghJCG8FFJkqm60Wj/Sbby49bn9xOkaI5w4D5lUM3zPJ4bGaU3+sh8knL99/Tf+1hAgcEu5Rz4koh7lhIn/uAS0vOLvMKOJntywdh7DsTHr+CoOiYj22TjAo+fBR/sQQf7K+bdKIixayPQRE3lyBCmGi/zimRfNaPDs58M/h2RQKbt3WPuuKOTyC22CJaSuYJ2kwvzaxvAgEyiDILIKtXB9Af3slF3HdZCRyEWGxS9wJkn2PE57yvY3IdjP1iLbvaFp82xf6SbFP91sm3zvTvdol3KiNub35zQZ7ZcZIbW+gBXJcP3bDVwu6KTHECZa1h+QzRxE0OKF9rS/0RDngVOEMex/0Fm1j11Zb0jLhTDGj3yhgvA32tmo0O+3RBNw9c0fDdxRK/cVOlQr1Re2f16jX5fY15EfNVW+/78Tpuqs=
