sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global: 
  secure: KRbnUQB4CIM5cJm0Z+7JmArRNpDPEg6s9xT+Hsf7dNvcJAJRG62OcJETCObyR40COrjJxdtdE2PQed4+31l35MjKG7aEqg7cRhK1o7o/s3g982UqRcYE2OrV7aPr8xv/2uSZAGY9uBkVgUqZfPjm1f+8pUv0kUjj6BWfNXMT3w8rUNKnzTrrlN1+kChGHfGJU4QwSFI5yojJVvBuy4bgjFKbe+x5SRv1FRH9ycOf8zpOAzJXLxnl0C/whRnGruRX7xa49zxOzY+Ndp2roXKccbdYVFqYw7Q8sc+Uh7JaMEUrdkkImPRZv0r/ctDGg5zTuRK5qkh3LH3g3EM5hVZHwn2ROzkc96/IUfiNMQvGrbmCABCtLE8Ot83os0Fvqjzvchw/AtvN5qNS355NKzFYdBmYioDSsorsLVJA5lpgDfOU6creDuhr+S1Y4VZ/IbJOJitCnM7zjcswjybwZbOGC4ICVdyg6GtN2S8uRbhvd02ucsFFLj51u9E3rO8sdOYQhVHy/zoqhjgG2zFFlayonlJ1Z6iDXh/gFG/VSDqfrOvimjYto8lVqjwGCytVNYt/VUCqf14Az/U+0cr38QIB39QsUBxWnNMpUTtSdPxoL/oVw5Ys949zmCo7bYER2rntGxTH6YTkUgQ1hjRukT7iCC6neiL4Qe9mFOIPcfn9Ay4=
branches:
  only:
  - source
dd:
  secure: SQwiFBbchE19+KbaVvsQyrtnMnK7GZDRoeie1VK1yq4t3b4Ubo6tzemnGayZbQlnrwLVVa7+pBpJtgnn+w0Dyo4DwmrC0OKJTuvgZriU7uaS9eefBALr9c2HNECm43pp0tXOytrsoaq6EKeV897KInTgWcmuwqpxmemFOSOXmOyC/FS0UdGzvSowE+uCLIU0MPQvFik2PZUBWbmlCzLipfT+hLU829yh+e+WfLw8QSTEjoCRt2g+L0cRPKVaWspZAnKK3wLsISnXwwizJ/lhnUwsYimRzmt8R65ToioVlWXXVKxAcDiu1+JtalZ3rln4yIqTYIJsd0ShN39I8kOVA8FEzCeARsuv4oWJmCzxjO8XDFZOl+NjOD1cpJpaMf4uaUfEsbIHWWZJtejzgMkytmlChAYVnzm16NHIkcF9tSBW89YWLHqgMKwOA4+BUzPqItRtPMLqyobDGi06lRZeqbhHgHU6uobeOzxA2iuU/MkrEe3j8fG+mJfvWiOmpDaQATyrUeS/SsegFjvyW7DLRWBOLm0RjrUis9ZZWovAQoMf3uv08X8MnKzCu3o/Uq/fUotcr0gSQmwoEj4R3dw7qXtxA8e3tgcBoza/PQXGsNUOT0AdjVDIi6pth0RKWA7eN1xfbROtMuzcO9pBPgnHgwcYE/ediQWfmXdXdbhHL/4=
