sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2
install:
- bundle install
script: bundle exec rake site:deploy --quiet
dd:
  secure: "SQwiFBbchE19+KbaVvsQyrtnMnK7GZDRoeie1VK1yq4t3b4Ubo6tzemnGayZbQlnrwLVVa7+pBpJtgnn+w0Dyo4DwmrC0OKJTuvgZriU7uaS9eefBALr9c2HNECm43pp0tXOytrsoaq6EKeV897KInTgWcmuwqpxmemFOSOXmOyC/FS0UdGzvSowE+uCLIU0MPQvFik2PZUBWbmlCzLipfT+hLU829yh+e+WfLw8QSTEjoCRt2g+L0cRPKVaWspZAnKK3wLsISnXwwizJ/lhnUwsYimRzmt8R65ToioVlWXXVKxAcDiu1+JtalZ3rln4yIqTYIJsd0ShN39I8kOVA8FEzCeARsuv4oWJmCzxjO8XDFZOl+NjOD1cpJpaMf4uaUfEsbIHWWZJtejzgMkytmlChAYVnzm16NHIkcF9tSBW89YWLHqgMKwOA4+BUzPqItRtPMLqyobDGi06lRZeqbhHgHU6uobeOzxA2iuU/MkrEe3j8fG+mJfvWiOmpDaQATyrUeS/SsegFjvyW7DLRWBOLm0RjrUis9ZZWovAQoMf3uv08X8MnKzCu3o/Uq/fUotcr0gSQmwoEj4R3dw7qXtxA8e3tgcBoza/PQXGsNUOT0AdjVDIi6pth0RKWA7eN1xfbROtMuzcO9pBPgnHgwcYE/ediQWfmXdXdbhHL/4="

branches:
  only:
  - source
