sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global: 
dd:
  secure: G5wowPPGO/opT3tgt8LPRRqeQgyV8+WDpiqjlyM0g5YL7RSIf+5T3O8Gs6jLKNZGRlwGXDJSYEOkNTdiPm6XRmWlABXpre1F1xOEJKuPVXh4Kj0KQJ6N3IWcffApW3cv+sNo3NiaBt77/gTBzPMqGootZ7VXMQ7Y7CepLP/zMC6k92xCGxsPVSCGgZctoMGVw4H5nI0J3uQIhG/MpNFf/IDSaoHfpzXl81ncgrpSEtVN2nZ5upCH1N5kJP3OK5+tObO/Dcv/xe9xQbWas1C8Wxkf6+lp0ZTb62Ec8M0JR/BKfR7VSyn6rHg3T3/wmTFKjZc72z5G10tW2zx7rezGDwn5VznVa4sGFk/fUdZoiFWKLQjT0Ygnq/dpc/dv6jWO6QKn74KhJATWyYE89ZJ7R8D68wHog8bEiRCfpUWygVQ3zrTLjheY6YCgEyg5qi4NVNHUa/3ZUmgduGb05BMnmmO2uvteIAQuMocJApTRCUTmv1Z3HNob+WEe5gnwJNE2yw+Xk1h2Sd8KXsU8KRTK/fb+4lB5RIb/N4NzOFlvdCoCxLmsF+tUXVL+WimTbG/FOB1NVwMLWQr8CUCv7bY6s4u8JHbkzSCq+lxXGJ30Mo4Xd/Uqogbb5sKm/d8rKfe7v8jQkwyWYkdhDr9YWt9MIEFYEf3IwcZVcERF7nV/5S0=
