sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global: 
dd:
  secure: XOK2yBgTgmLf/0jecv5CIPptSD+pTwbe+EAox6qbZPwpKXnwo7WE6qfjmANm+6o86C60H38djEtevI7ASPs5foFN09+MMx9Mt70ilbQfISCgmKaPcN4af7Vjzwc572SDGIvPXyYw7Ing5WwIuKnSilwyrRPSXm47+u4/1ya+neh7KD3FkLDlwXqHChuUT5gE/90U9mLwN0VppVN0+AFPHELtYfb9lLvAVfOTGWNMSuRfpGnXAoO17nf28d/mR118to6Vl5gKgmEYMRENrWQt9xdj5m9v2BJ5TNGG8QCvHYPLmQQFflFR5Y7FBjDLym4fclDlIAteg5rkQEgS+y2QEV2rwb1zEjVZGBQrBgLiEgaDPYKGzz3QSIYHchAT2yOrOACrfw7BKSHM+glJ+MULYHsD070siUrNnkHJtyy28mGPSpkP5ob2YQfNtV/+jqCJkmPUqB8MPC2KwuX+PDCQKMy6u1cCf7/gmawN0sTpYvs0egQ6t/kwsb58ut085cZ7KIoAzanYwfzMccLPuSx+h2FO3PXXlQBw+RtP9P/BOBoB17qKpIhKvOrhBakf9fEJ96fWJn0UnNp/xniikYLJTwssC03b4ztcpXffBnQPEoDuqZYEJNoL+BkWoz4f4nWmfRa0m9kJcMHYb3hxgajxW0/Qz/JoxF7I29VVsKhsamw=